### ISSUE TITLE
NSF CoPI Visualizations

### ISSUE THREAD

**Issue by ProfessorPolymorphic** [ui-insight/UI_PI_CoPI#12]
Using the NSF Data from #2 , @cambarerij will create new versions of his visualizations using our active NSF grants.

This will involve the following steps.

- [x] Import NSF data into a new python workbook or file
- [x] Clean the NSF data.  We don't need a bunch of columns like City, Middle initial, county, etc.  Use your best judgement.
- [x] Copy over the code necessary to create the visualizations from the previous notebook.
- [x] Integrate the new data with the visualization code.

**Comment by cambarerij** [comment]
Here is a picture of the kind of graph we want for this
![Screenshot 2024-10-22 at 9 38 10 AM](https://github.com/user-attachments/assets/abdbfb33-7b66-43b4-bf27-5e3b559ff731)
