### ISSUE TITLE
NSF API data

### ISSUE THREAD

**Issue by ProfessorPolymorphic** [ui-insight/UI_PI_CoPI#2]
Download UI award data from the NSF API.

- [x] Barrie provides example code
- [x] John converts to Python and executes
- [x] John uploads data and python code to repository.

**Comment by ProfessorPolymorphic** [comment]
@cambarerij I've added the files for the NSF API.  The code is in the .qmd file.

**Comment by cambarerij** [comment]
R code converted to Python Code; Data downloaded from NSF successfully

**Comment by cambarerij** [comment]
Uploaded Python code + UINSF.csv
