### ISSUE TITLE
Send FDP Session Video

### ISSUE THREAD

**Issue by mmattoonui** [ui-insight/UI_PI_CoPI#5]

**Comment by mmattoonui** [comment]
Please send the FDP session video on NSF AI tools to the team once available. Then move this to the Done column.

**Comment by smartonick** [comment]
[FDP-AI-Brief-240918.pdf](https://github.com/user-attachments/files/17624976/FDP-AI-Brief-240918.pdf)

AI brief added. Looking for recordings.
